name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: isPrimeCorrect
      id: isprimecorrect
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: isPrimeCorrect
        setup-command: ''
        command: gradle test --tests "*isPrimeCorrect*"
        timeout: 10
    - name: first10DigitPrimeInETest
      id: first10digitprimeinetest
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: first10DigitPrimeInETest
        setup-command: ''
        command: gradle test --tests "*first10DigitPrimeInETest*"
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ISPRIMECORRECT_RESULTS: "${{steps.isprimecorrect.outputs.result}}"
        FIRST10DIGITPRIMEINETEST_RESULTS: "${{steps.first10digitprimeinetest.outputs.result}}"
      with:
        runners: isprimecorrect,first10digitprimeinetest
